feat: fisheye accepts abstract focus point instead of visual focus point
antvis/coord pull request #40
Opened 2022-08-16 10:24 UTC by pepper-nice

### Features
Fisheye position supports abstract point and actual visual point.

### API
```ts
params: {
  focusX: number;
  focusY: number;
  distortionX: number;
  distortionY: number;
  /** whether focus is visual point */
  isVisual?: boolean
}
```
### Usage
```js
const coord = new Coordinate({
  width: '150px',
  height: '300px'
});

// 1. use relative point
coord.transform('fisheye', 0.5, 0.5, 2, 2);
coord.transform('cartesian');

// 2. use visual point
coord.transform('fisheye', 100, 100, 2, 2, true);
coord.transform('cartesian');
```

### Effects

|  relative point   |  visual point  |
|  ----  | ----  |
| ![iShot_2022-08-16_18 11 08](https://user-images.githubusercontent.com/109653633/184854851-e8471578-2de6-4f4d-ae1b-96ba2b873f2e.gif) | ![iShot_2022-08-16_18 21 57](https://user-images.githubusercontent.com/109653633/184857010-bf7244d9-18b2-47dc-9b1f-5a4f8cc45c13.gif) |

2022-08-16 12:24 UTC, pearmini requested changes
写的挺好的，记得去改一下文档里面的[例子](https://github.com/antvis/coord/blob/master/docs/api/transformations.md#fisheye-lens)。还可以顺便给 `fisheye.circular` 也做相同的修改。👍

2022-08-16 12:24 UTC, pearmini commented on src/transforms/fisheye.ts
> +  return focus;
实现函数的一个原则就是把简单或者特殊情况（参数检查等）放在最前面，所以这个函数更好的写法是：
```js
function normalize(...) {
  if (!isVisual) return focus;
  // ...
}
```

2022-08-16 12:24 UTC, pearmini commented on src/transforms/fisheye.ts
> +  const normalizedFocusX = normalize(focus, width, isVisual as boolean);
这里最好不要用 as，这应该是我之前实现的问题，更好的做法是直接显示声明参数的类型，这样 isVisual 参数后面也不用 as。

```js
// 方案一
const [focus, distortion, isVisual = false]: [number, number, boolean?] = params;
```

当然更好的做法是给 CreateTransformer 这个类型传入一个泛型，根据这个泛型自动去推断参数的类型。

```js
// 方案二
import {Fisheye} from "../types';

const fisheyeX: CreateTransformer<Fisheye> = (params, x, y, width, height) => {}
```

这里就暂时先用方案一就好，

2022-08-16 21:57 UTC, visiky commented on src/transforms/fisheye.ts
> +  const normalizedFocusX = normalize(focus, width, isVisual as boolean);
方案一挺好的

2022-08-18 10:55 UTC, pearmini commented on src/transforms/fisheye.ts
> +      return [normalizedFocusX + r * Math.cos(theta), normalizedFocusY + r * Math.sin(theta)];
这里一个比较简单的思路就是：先把 focusX 和 focusY 转换成画布坐标，然后进行鱼眼变换，然后在转换成归一化的数据。

```js
const visualX = unnormalize(focusX, width, isVisual as boolean);
const visualY = unnormalize(focusY, width, isVisual as boolean);
//  原有逻辑，获得 fiseyeX 和 fisheyeY
return [normalize(fiseyeX), normalize(fisheyeY)]
```

这样虽然看上去都转换了一次，有点性能上的损耗。但是在处理椭圆相关计算本身也会有额外的计算开销，同时也保证了更好的可读性。

2022-08-18 12:13 UTC, closed without merging