feat: transpose3D
antvis/coord pull request #46
Opened 2023-11-19 16:53 UTC by VirusPC

新增加了 3D 版本的 `transpose`：`transpose3D`，希望能为以下效果提供支持：
https://www.anychart.com/products/anychart/gallery/3D_Bar_Charts/Multi-Series_3D_Bar_Chart_with_Z_Distribution.php
![image](https://github.com/antvis/coord/assets/30697592/bf6e4416-e476-4918-8206-33ad3dcbc137)

- 使用方式和 `transpose` 一致
```ts
const coord = new Coordinate3D();
coord.transform('transpose3D');
```
- 测试用例已补充

2023-11-21 01:58 UTC, pearmini approved these changes
优秀！

2023-11-21 01:59 UTC, pearmini requested changes
- pnpm-lock.yaml 可以去掉
- package.json 升级为 0.4.7 ?

2023-11-22 15:19 UTC, VirusPC commented
> * pnpm-lock.yaml 可以去掉
> * package.json 升级为 0.4.7 ?

已更新 :smile:

2023-11-23 09:47 UTC, pearmini approved these changes
🚀🚀🚀

2023-11-23 09:47 UTC, merged